import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/theme/providers";
import Header from "./components/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
         <div className="absolute inset-0 bg-[url('/light_background.jpg')] dark:bg-[url('/dark_background.jpg')] bg-cover bg-center blur-sm" />
         <div className="relative z-10"><Providers>
          <Header />
          {children}
        </Providers></div>
         
      </body>
    </html>
  );
}
