version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app/web

  front:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: nest_app
    restart: always
    volumes:
      - ./frontend:/app/web
    ports:
      - '3000:3000'